services:
  backend:
    build:
      context: ./backend
    container_name: a1tiexamprism_backend

    ports:
      - "8000:8000"

    volumes:
      - /root/data/a1tiexamprism:/app/database

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: a1tiexamprism_frontend

    depends_on:
      - backend

    ports:
      - "3000:80"

<<<<<<< HEAD
    restart: unless-stopped
=======
    restart: unless-stopped
>>>>>>> 9a4376b (first commit from local repo after pipeline made with backup)
